Widget Weather/Models/ErrorViewModel.cs
namespace Widget_Weather.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Widget Weather/Models/WeatherViewModel.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Web;
using Newtonsoft.Json;
using System.Text.Json.Serialization;

// Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
namespace Widget_Weather.Models
{
    // Root myDeserializedClass = JsonSerializer.Deserialize<Root>(myJsonResponse);
    public class Datum
    {
        [JsonPropertyName("rh")]
        public double Rh { get; set; }

        [JsonPropertyName("pod")]
        public string Pod { get; set; }

        [JsonPropertyName("lon")]
        public double Lon { get; set; }

        [JsonPropertyName("pres")]
        public double Pres { get; set; }

        [JsonPropertyName("timezone")]
        public string Timezone { get; set; }

        [JsonPropertyName("ob_time")]
        public string ObTime { get; set; }

        [JsonPropertyName("country_code")]
        public string CountryCode { get; set; }

        [JsonPropertyName("clouds")]
        public double Clouds { get; set; }

        [JsonPropertyName("ts")]
        public double Ts { get; set; }

        [JsonPropertyName("solar_rad")]
        public double SolarRad { get; set; }

        [JsonPropertyName("state_code")]
        public string StateCode { get; set; }

        [JsonPropertyName("city_name")]
        public string CityName { get; set; }

        [JsonPropertyName("wind_spd")]
        public double WindSpd { get; set; }

        [JsonPropertyName("wind_cdir_full")]
        public string WindCdirFull { get; set; }

        [JsonPropertyName("wind_cdir")]
        public string WindCdir { get; set; }

        [JsonPropertyName("slp")]
        public double Slp { get; set; }

        [JsonPropertyName("vis")]
        public double Vis { get; set; }

        [JsonPropertyName("h_angle")]
        public double HAngle { get; set; }

        [JsonPropertyName("sunset")]
        public string Sunset { get; set; }

        [JsonPropertyName("dni")]
        public double Dni { get; set; }

        [JsonPropertyName("dewpt")]
        public double Dewpt { get; set; }

        [JsonPropertyName("snow")]
        public double Snow { get; set; }

        [JsonPropertyName("uv")]
        public double Uv { get; set; }

        [JsonPropertyName("precip")]
        public double Precip { get; set; }

        [JsonPropertyName("wind_dir")]
        public double WindDir { get; set; }

        [JsonPropertyName("sunrise")]
        public string Sunrise { get; set; }

        [JsonPropertyName("ghi")]
        public double Ghi { get; set; }

        [JsonPropertyName("dhi")]
        public double Dhi { get; set; }

        [JsonPropertyName("aqi")]
        public double Aqi { get; set; }

        [JsonPropertyName("lat")]
        public double Lat { get; set; }

        [JsonPropertyName("weather")]
        public Weather Weather { get; set; }

        [JsonPropertyName("datetime")]
        public string Datetime { get; set; }

        [JsonPropertyName("temp")]
        public double Temp { get; set; }

        [JsonPropertyName("station")]
        public string Station { get; set; }

        [JsonPropertyName("elev_angle")]
        public double ElevAngle { get; set; }

        [JsonPropertyName("app_temp")]
        public double AppTemp { get; set; }
    }

    public class Root
    {
        [JsonPropertyName("data")]
        public List<Datum> Data { get; set; }

        [JsonPropertyName("count")]
        public double Count { get; set; }
    }

    public class Weather
    {
        [JsonPropertyName("icon")]
        public string Icon { get; set; }

        [JsonPropertyName("code")]
        public double Code { get; set; }

        [JsonPropertyName("description")]
        public string Description { get; set; }
    }



}

Widget Weather/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net;
using Widget_Weather.Models;

namespace Widget_Weather.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Widget Weather/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using Widget_Weather.Models;

namespace Widget_Weather.Controllers
{
    public class WeatherController: Controller
    {
        private readonly string apiKey = "yourApiKey";
        //static async Task CurrentWeather(string)
        /// <summary>
        /// 
        /// </summary>
        /// <param name="city"></param>
        /// <returns></returns>
        /// <exception cref="Exception"></exception>
        public async Task<IActionResult> Weather(string city)
        {
            HttpClient client = new HttpClient();
            if (string.IsNullOrEmpty(city))
                city = "Toulouse";
            
            {
                // Call asynchronous network methods in a try/catch block to handle exceptions.
                try
                {
                    HttpResponseMessage response = await client.GetAsync(string.Format("http://api.weatherbit.io/v2.0/current?city={0}&key={1}", city, apiKey));
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        string responseBody = await response.Content.ReadAsStringAsync();
                        var jsonResponse = JsonSerializer.Deserialize<Root>(responseBody);

                        return View(jsonResponse);
                    }

                    throw new Exception("C'est cassé chef !");
                }
                catch (HttpRequestException e)
                {
                    Console.WriteLine("\nException Caught!");
                    Console.WriteLine("Message :{0} ", e.Message);
                    throw new Exception(e.Message);
                }
            }
            
        }
        
    }
}

Widget Weather/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Widget Weather/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Widget_Weather</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Widget_Weather.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Widget_Weather</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Weather">Weather</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Widget_Weather - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Widget Weather/Views/Weather/Weather.cshtml
@model Root

@{
    ViewData["Weather"] = "Weather";
}
<h1>Search City and get weather </h1>

<form asp-controller="Weather" asp-action="Weather" method="post">
    <div>
    <label for="city">Enter city name :</label>
    <input type="text" name="city" id="city" />
    </div>
    <div>
    <input type="submit" value="Get weather" />
    </div>
</form>
<div>    
    <h2>Weather Forecast</h2>    
    <table>    
        
        <tr>    
            <td>    
                <strong>City : </strong><br /><br />
                <span id="lblCity">@Model?.Data?.FirstOrDefault()?.CityName</span>    
                <span id="lblCountry">@Model?.Data?.FirstOrDefault()?.CountryCode</span><br /><br />
            </td>    
        </tr>
        <tr>
            <td>
                <strong>Weather :</strong>
                <br /><br />
                Weather description : <label id="lblWeatherDesc">@Model?.Data?.FirstOrDefault()?.Weather.Description</label><br />
                Temperature : <label id="lblTemp">@Model?.Data?.FirstOrDefault()?.Temp °C</label><br />
                Temperature (Feel) : <label id="lblFeelTemp">@Model?.Data?.FirstOrDefault()?.AppTemp °C</label><br />
                Humidity : <label id="lblHumidity">@Model?.Data?.FirstOrDefault()?.Rh %</label><br />
                Cloud coverage : <label id="lblCloudCoverage">@Model?.Data?.FirstOrDefault()?.Clouds %</label><br /><br />       
            </td>
            
        </tr>
        <tr>
            <td>
                <strong>Wind :</strong><label id="lblWind"></label>
                <br />
                <br />
                Wind Strength : <label id="lblWindStrength">@Model?.Data?.FirstOrDefault()?.WindSpd m/s</label><br />
                Wind Direction : <label id="lblWindDirection">@Model?.Data?.FirstOrDefault()?.WindCdir</label><br /><br /> 
            </td>
        </tr>
        <tr>
            <td>
                <strong>Sunset/sunrise</strong><label id="lblSun"></label>
                <br />
                <br />
                Sunrise time : <label id="lblSunrise">@Model?.Data?.FirstOrDefault()?.Sunrise</label><br />
                Sunset time : <label id="lblSunset">@Model?.Data?.FirstOrDefault()?.Sunset</label>
            </td>
        </tr>
    </table>
</div>